// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
// import { Button } from '@/components/ui/button'
// import {FolderIcon, Heart, ImageIcon } from 'lucide-react'
// import Link from 'next/link'
// import cloudinary from "cloudinary"
// import {Folder} from "@/app/albums/page"
// import Image from "next/image"

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


// async function SideMenu() {
//   const {folders} = (await cloudinary.v2.api.root_folders()) as {
//     folders : Folder[]
// }
//   return (
//     <div className="pb-12 w-1/5">
//       <div className="space-y-4 py-4">
//         <div className="px-3 py-2">
//           <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
//             Manage
//           </h2>
//           <div className="space-y-1">
//             <Button asChild
//               variant="ghost" className="w-full justify-start flex gap-2">
//               <Link href="/gallery">
//                 <ImageIcon />
//                 Gallery</Link>
//             </Button>
//             <Button asChild variant="ghost" className="w-full justify-start flex gap-2">
//               <Link href="/albums">
//                 <FolderIcon />
//                 Albums
//               </Link>
//             </Button>
//             {folders.map(folder => <Button variant="ghost"
//              asChild
//             key={folder.name}
//             className="w-full justify-start flex gap-2">
//               <Link className="pl-8"
//                href={`/albums/${folder.path}`}>
//                 {folder.name}
//               </Link>
//             </Button>)}
//             <Button asChild
//               variant="ghost" className="w-full justify-start flex gap-2">
//               <Link href="/favorites">
//                 <Heart />
//                 Favorites
//               </Link>
//             </Button>
//           </div>
//         </div>
//       </div>
//     </div>
//   )
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" className="dark">
//       <body className={inter.className}>
//         <div className="border-b ">
//           <div className="flex h-16 items-center px-4 container mx-auto">
//             <Image src="/album.png" width="50" height="50" alt="Icon of this photo album app"/>
//             PURE PIXELS
//             <div className="ml-auto flex items-center space-x-4">
//               <Avatar>
//                 <AvatarImage src="https://github.com/shadcn.png" />
//                 <AvatarFallback>CN</AvatarFallback>
//               </Avatar>

//             </div>
//           </div>
//         </div>

//         <div className="flex ">
//           <SideMenu />
//           <div className="w-full px-4 pt-12">
//             {children}
//           </div>
//         </div>
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import {FolderIcon, Heart, HomeIcon, ImageIcon, Menu } from 'lucide-react'
import Link from 'next/link'
import cloudinary from "cloudinary"
import {Folder} from "@/app/albums/page"
import Image from "next/image"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


async function SideMenu() {
  const {folders} = (await cloudinary.v2.api.root_folders()) as {
    folders : Folder[]
}
  return (
   <div>
     <div className="pb-12 w-1/5 hidden md:flex">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1">
            <Button asChild
              variant="ghost" className="w-[110%] justify-start flex gap-2">
             <Link href="/">
                <HomeIcon />
                Home</Link>
            </Button>
            <Button asChild
              variant="ghost" className="w-[110%] justify-start flex gap-2">
              <Link href="/gallery">
                <ImageIcon />
                Gallery</Link>
            </Button>
            <Button asChild variant="ghost" className="w-[110%] justify-start flex gap-2">
              <Link href="/albums">
                <FolderIcon />
                Albums
              </Link>
            </Button>
            {folders.map(folder => <Button variant="ghost"
             asChild
            key={folder.name}
            className="w-[110%] justify-start flex gap-2">
              <Link className="pl-8"
               href={`/albums/${folder.path}`}>
                {folder.name}
              </Link>
            </Button>)}
            <Button asChild
              variant="ghost" className="w-[110%] justify-start flex gap-2">
              <Link href="/favorites">
                <Heart />
                Favorites
              </Link>
            </Button>
          </div>
          </div>
        </div>
      </div>
          <div className="flex md:hidden">
          <Sheet>
  <SheetTrigger className='px-2 py-2'><Menu/></SheetTrigger>
  <SheetContent>
    <SheetHeader>
      {/* w-1/5 */}
    <div className="pb-12 "> 
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1 ">
          <Button asChild
            variant="ghost" className=" justify-start flex gap-2 w-[80%] items-center">
              <Link href="/">
                <HomeIcon />
                Home</Link>
            </Button>
            <Button asChild
              variant="ghost" className=" justify-start flex gap-2 w-[80%] items-center">
              <Link href="/gallery">
                <ImageIcon />
                Gallery</Link>
            </Button>
            <Button asChild variant="ghost" className=" w-[80%] bg-black/5 justify-start flex gap-2">
              <Link href="/albums">
                <FolderIcon />
                Albums
              </Link>
            </Button>
            {folders.map(folder => <Button variant="ghost"
             asChild
            key={folder.name}
            className="w-[80%] justify-start flex gap-2">
              <Link className="pl-8"
               href={`/albums/${folder.path}`}>
                {folder.name}
              </Link>
            </Button>)}
            <Button asChild
              variant="ghost" className=" w-[80%] justify-start flex gap-2">
              <Link href="/favorites">
                <Heart />
                Favorites
              </Link>
            </Button>
          </div>
          </div>
        </div></div>
    </SheetHeader>
  </SheetContent>
</Sheet>

         
    </div>
   </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b ">
          <div className="flex h-16 items-center px-4 container mx-auto">
            <Image src="/album.png" width="50" height="50" alt="Icon of this photo album app"/>
            PURE PIXELS
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>

            </div>
          </div>
        </div>

        <div className="flex ">
          <SideMenu />
          <div className="w-full px-4 pt-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
